openapi: 3.0.0
info:
  title: Spring cloud contract Open API Test
  description: Testing Spring cloud contract Open API
  version: "1.0"
servers:
  - url: https://development.gigantic-server.com/v1
    description: Development server
paths:
  /hello:
    get:
      summary: Get Hello
      x-contracts:
        - contractId: 1
          name: Should Get Hello
      responses:
        '200':
          description: Get ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  key1:
                    type: string
          x-contracts:
            - contractId: 1
              body:
                "key1": "val1"