swagger: "2.0"
info:
  title: Foo API
  version: v1
host: api.example.com
produces:
  - application/json;charset=UTF-8
consumes:
  - application/json;charset=UTF-8
tags:
  - name: Foo
    description: Foo Operations
paths:
  /foos:
    $ref: "./foos.yaml#/List"
  /foos/{fooId}:
    $ref: "./foos.yaml#/Get"